apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infa/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: npn/ticket-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: npn/ticket-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.css"
portForward:
  - resourceType: deployment
    resourceName: ticket-client
    port: 3000
